
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    profiles:
      - tracing
    volumes:
      - ./mlflow.db:/mlflow/db
      - ./mlartifacts:/mlflow/mlartifacts
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow/db/mlflow.db
      --artifacts-destination /mlflow/mlartifacts
